//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.225 版自动生成。
// 
#pragma warning disable 1591

namespace WebUI.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="jzfkSoap11Binding", Namespace="http://service.jzjk.com")]
    public partial class jzfk : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback updateStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public jzfk() {
            this.Url = global::WebUI.Properties.Settings.Default.WebUI_WebReference_jzfk;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event updateStatusCompletedEventHandler updateStatusCompleted;
        
        /// <remarks/>
        public event updateServiceCompletedEventHandler updateServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:updateStatus", RequestNamespace="http://service.jzjk.com", ResponseNamespace="http://service.jzjk.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string updateStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AJBH, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string WSID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string STATUS) {
            object[] results = this.Invoke("updateStatus", new object[] {
                        AJBH,
                        WSID,
                        STATUS});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateStatusAsync(string AJBH, string WSID, string STATUS) {
            this.updateStatusAsync(AJBH, WSID, STATUS, null);
        }
        
        /// <remarks/>
        public void updateStatusAsync(string AJBH, string WSID, string STATUS, object userState) {
            if ((this.updateStatusOperationCompleted == null)) {
                this.updateStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateStatusOperationCompleted);
            }
            this.InvokeAsync("updateStatus", new object[] {
                        AJBH,
                        WSID,
                        STATUS}, this.updateStatusOperationCompleted, userState);
        }
        
        private void OnupdateStatusOperationCompleted(object arg) {
            if ((this.updateStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateStatusCompleted(this, new updateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:updateService", RequestNamespace="http://service.jzjk.com", ResponseNamespace="http://service.jzjk.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string updateService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string AJBH, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string JZFJNAME, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string JZFJPATH, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SCBJ, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string WSID) {
            object[] results = this.Invoke("updateService", new object[] {
                        AJBH,
                        JZFJNAME,
                        JZFJPATH,
                        SCBJ,
                        WSID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateServiceAsync(string AJBH, string JZFJNAME, string JZFJPATH, string SCBJ, string WSID) {
            this.updateServiceAsync(AJBH, JZFJNAME, JZFJPATH, SCBJ, WSID, null);
        }
        
        /// <remarks/>
        public void updateServiceAsync(string AJBH, string JZFJNAME, string JZFJPATH, string SCBJ, string WSID, object userState) {
            if ((this.updateServiceOperationCompleted == null)) {
                this.updateServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateServiceOperationCompleted);
            }
            this.InvokeAsync("updateService", new object[] {
                        AJBH,
                        JZFJNAME,
                        JZFJPATH,
                        SCBJ,
                        WSID}, this.updateServiceOperationCompleted, userState);
        }
        
        private void OnupdateServiceOperationCompleted(object arg) {
            if ((this.updateServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateServiceCompleted(this, new updateServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateStatusCompletedEventHandler(object sender, updateStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateServiceCompletedEventHandler(object sender, updateServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591